version: '3.3'

# Usage:
#   docker stack deploy -c stack.yml mongo
# or
#   docker-compose -f stack.yml up

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo-docker
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: )j2*((__4BS
      #MONGODB_AUTH_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume/workspace:/workspace
      - ./mongo-volume/data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: (234)**(wWQEfs
      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: )j2*((__4BS
      ME_CONFIG_MONGODB_URL: mongo://mongoadmin:)j2*((__4BS@mongo:27017/
    depends_on:
      - mongo